# Site settings
title: Iain Mckay
description: 'Developer. Geek. Dad.'
url: 'https://www.iainmckay.co.uk'
baseurl: ''
encoding: utf-8
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Iain Mckay'
  email: me@iainmckay.co.uk
  twitter_username: ~
  facebook_username: ~
  github_username:  iainmckay
  linkedin_username:  iainmckay

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'docker-compose.yml', 'LICENSE', 'vendor']
